(function(){const T='Week 7: Quadratic Functions',Q=[
{id:7101,topic:T,question:'Sketch $f(x) = x^2 - 4x + 3$. Find the vertex, x-intercepts and y-intercept.',markingCriteria:[{type:'value',expected:2,tolerance:0.01,description:'vertex x=2',marks:1},{type:'value',expected:-1,tolerance:0.01,description:'vertex y=-1',marks:1},{type:'contains',expected:['x=1','x=3'],description:'x-intercepts 1 and 3',marks:1},{type:'value',expected:3,tolerance:0.01,description:'y-int=3',marks:1}],easyTemplate:'<div class="memo-line">Vertex: $x = \\frac{4}{2} = @INPUT@$; $f(@INPUT@) = @INPUT@$</div><div class="memo-line">x-ints: $x^2-4x+3=(x-@INPUT@)(x-@INPUT@)=0$</div><div class="memo-line">y-int: $f(0) = @INPUT@$</div>',hardTemplate:'Vertex (@INPUT@,@INPUT@), x-ints @INPUT@, y-int @INPUT@',memo:'<div class="memo-line">Vertex (2,−1); x-ints 1,3; y-int 3 <span class="memo-mark">✓(4)</span></div>'},
{id:7102,topic:T,question:'Use the quadratic formula to solve $2x^2 - 7x + 3 = 0$.',markingCriteria:[{type:'value',expected:3,tolerance:0.01,description:'x=3',marks:1},{type:'value',expected:0.5,tolerance:0.01,description:'x=0.5',marks:1}],easyTemplate:'<div class="memo-line">$x = \\frac{7 \\pm \\sqrt{49-@INPUT@}}{@INPUT@} = \\frac{7 \\pm @INPUT@}{4}$</div><div class="memo-line">$x = @INPUT@$ or $x = @INPUT@$</div>',hardTemplate:'x=@INPUT@ or x=@INPUT@',memo:'<div class="memo-line">x=3 or x=0.5 <span class="memo-mark">✓(2)</span></div>'},
{id:7103,topic:T,question:'Determine the discriminant of $3x^2 + 5x + 2 = 0$ and state the nature of roots.',markingCriteria:[{type:'value',expected:1,tolerance:0.01,description:'Δ=1',marks:1},{type:'contains',expected:['two real','two distinct'],description:'Two distinct real roots',marks:1}],easyTemplate:'<div class="memo-line">$\\Delta = b^2 - 4ac = (@INPUT@)^2 - 4(@INPUT@)(@INPUT@) = @INPUT@ - @INPUT@ = @INPUT@$</div><div class="memo-line">$\\Delta @INPUT@ 0$ → @INPUT@ roots</div>',hardTemplate:'Δ=@INPUT@, Roots: @INPUT@',memo:'<div class="memo-line">Δ=1>0 → two distinct real roots <span class="memo-mark">✓(2)</span></div>'},
{id:7104,topic:T,question:'A parabola has vertex at $(3,-4)$ and passes through $(5,0)$. Find its equation in vertex form and standard form.',markingCriteria:[{type:'contains',expected:['(x-3)²','(x-3)^2'],description:'vertex form with (x-3)²',marks:2},{type:'value',expected:1,tolerance:0.01,description:'a=1',marks:1}],easyTemplate:'<div class="memo-line">Vertex form: $f(x) = a(x-@INPUT@)^2 + (@INPUT@)$</div><div class="memo-line">Sub $(5,0)$: $0 = a(2)^2 - 4 \\Rightarrow a = @INPUT@$</div><div class="memo-line">$f(x) = (x-3)^2 - 4 = @INPUT@$</div>',hardTemplate:'f(x) = @INPUT@',memo:'<div class="memo-line">f(x)=(x−3)²−4=x²−6x+5 <span class="memo-mark">✓(3)</span></div>'},
{id:7105,topic:T,question:'Revenue: $R(p) = -2p^2 + 100p$ where $p$ is price. Find the price that maximises revenue.',markingCriteria:[{type:'value',expected:25,tolerance:0.01,description:'p=25',marks:2},{type:'value',expected:1250,tolerance:0.5,description:'Max R=R1250',marks:2}],easyTemplate:'<div class="memo-line">$R\'(p) = -4p + 100 = 0$</div><div class="memo-line">$p = \\frac{@INPUT@}{@INPUT@} = @INPUT@$</div><div class="memo-line">$R(@INPUT@) = -2(@INPUT@)^2 + 100(@INPUT@) = R@INPUT@$</div>',hardTemplate:'p=@INPUT@, Max R=R@INPUT@',memo:'<div class="memo-line">p=25, R=R1250 <span class="memo-mark">✓(4)</span></div>'},
{id:7106,topic:T,question:'Solve $x^2 - 9 = 0$ by factorisation. State x-intercepts of $y = x^2 - 9$.',markingCriteria:[{type:'value',expected:3,tolerance:0.01,description:'x=3',marks:1},{type:'value',expected:-3,tolerance:0.01,description:'x=-3',marks:1}],easyTemplate:'<div class="memo-line">$(x-@INPUT@)(x+@INPUT@) = 0$</div><div class="memo-line">$x = @INPUT@$ or $x = @INPUT@$</div>',hardTemplate:'x=@INPUT@ or x=@INPUT@',memo:'<div class="memo-line">x=3 or x=−3 <span class="memo-mark">✓(2)</span></div>'},
{id:7107,topic:T,question:'A projectile is launched with height $h(t) = -4.9t^2 + 30t + 1.5$ metres. What is the maximum height? When is it reached?',markingCriteria:[{type:'value',expected:3.061,tolerance:0.01,description:'t≈3.06s',marks:2},{type:'value',expected:47.4,tolerance:0.5,description:'Max h≈47.4m',marks:2}],easyTemplate:'<div class="memo-line">$h\'(t) = -9.8t + 30 = 0$; $t = \\frac{@INPUT@}{@INPUT@} \\approx @INPUT@$ s</div><div class="memo-line">$h(@INPUT@) \\approx @INPUT@$ m</div>',hardTemplate:'t=@INPUT@s, Max h=@INPUT@m',memo:'<div class="memo-line">t≈3.06s; max h≈47.4m <span class="memo-mark">✓(4)</span></div>'},
{id:7108,topic:T,question:'Complete the square: $x^2 + 8x + 5$. Write in vertex form.',markingCriteria:[{type:'contains',expected:['(x+4)²','(x+4)^2'],description:'(x+4)²',marks:1},{type:'value',expected:-11,tolerance:0.01,description:'−11',marks:1}],easyTemplate:'<div class="memo-line">$x^2+8x+5 = (x^2+8x+@INPUT@) - @INPUT@ + 5$</div><div class="memo-line">$= (x+@INPUT@)^2 + @INPUT@$</div>',hardTemplate:'$(x+@INPUT@)^2 + @INPUT@$',memo:'<div class="memo-line">$(x+4)^2-11$ <span class="memo-mark">✓(2)</span></div>'},
{id:7109,topic:T,question:'For $f(x) = -x^2 + 6x - 5$, find: (a) vertex (b) axis of symmetry (c) range.',markingCriteria:[{type:'value',expected:3,tolerance:0.01,description:'vertex x=3',marks:1},{type:'value',expected:4,tolerance:0.01,description:'vertex y=4',marks:1},{type:'contains',expected:['x = 3'],description:'axis x=3',marks:1},{type:'contains',expected:['y ≤ 4','(-∞,4]'],description:'Range: y≤4',marks:1}],easyTemplate:'<div class="memo-line">Vertex: $x = \\frac{-6}{2(-1)} = @INPUT@$; $f(@INPUT@) = @INPUT@$</div><div class="memo-line">Axis: $x = @INPUT@$; Range: $y \\leq @INPUT@$</div>',hardTemplate:'Vertex (@INPUT@,@INPUT@), Axis x=@INPUT@, Range y≤@INPUT@',memo:'<div class="memo-line">Vertex (3,4); axis x=3; range y≤4 <span class="memo-mark">✓(4)</span></div>'},
{id:7110,topic:T,question:'A rectangle has perimeter 60 m. Let width $= x$. Length $= 30-x$. Find the dimensions maximising area.',markingCriteria:[{type:'value',expected:15,tolerance:0.01,description:'x=15',marks:2},{type:'value',expected:225,tolerance:0.5,description:'Max area=225m²',marks:2}],easyTemplate:'<div class="memo-line">$A(x) = x(30-x) = @INPUT@x - x^2$</div><div class="memo-line">$A\'(x) = @INPUT@ - @INPUT@x = 0$; $x = @INPUT@$</div><div class="memo-line">$A(@INPUT@) = @INPUT@$ m²</div>',hardTemplate:'x=@INPUT@m, Max A=@INPUT@m²',memo:'<div class="memo-line">x=15m (square); Max A=225m² <span class="memo-mark">✓(4)</span></div>'},
{id:7111,topic:T,question:'State the axis of symmetry for $f(x) = ax^2 + bx + c$.',markingCriteria:[{type:'contains',expected:['x = -b/2a','x=-b/(2a)'],description:'x=−b/2a',marks:2}],easyTemplate:'<div class="memo-line">Axis of symmetry: $x = \\frac{@INPUT@}{@INPUT@}$</div>',hardTemplate:'x = @INPUT@',memo:'<div class="memo-line">$x = -b/2a$ <span class="memo-mark">✓(2)</span></div>'},
{id:7112,topic:T,question:'Determine for what values of $k$ the equation $x^2 + kx + 9 = 0$ has two equal roots.',markingCriteria:[{type:'contains',expected:['k=6','k=-6','k = ±6'],description:'k=±6',marks:3}],easyTemplate:'<div class="memo-line">Equal roots: $\\Delta = 0$</div><div class="memo-line">$k^2 - 4(1)(9) = 0$</div><div class="memo-line">$k^2 = @INPUT@$; $k = \\pm@INPUT@$</div>',hardTemplate:'k = @INPUT@',memo:'<div class="memo-line">k=±6 <span class="memo-mark">✓(3)</span></div>'},
{id:7113,topic:T,question:'A firm\'s profit function is $\\pi(q) = -q^2 + 50q - 400$. Find breakeven quantities.',markingCriteria:[{type:'anyValue',expected:[10,40],tolerance:0.5,description:'q=10 or q=40',marks:3}],easyTemplate:'<div class="memo-line">Set $\\pi = 0$: $q^2 - @INPUT@q + @INPUT@ = 0$</div><div class="memo-line">$(q - @INPUT@)(q - @INPUT@) = 0$</div><div class="memo-line">$q = @INPUT@$ or $q = @INPUT@$</div>',hardTemplate:'BEP: q=@INPUT@ and q=@INPUT@',memo:'<div class="memo-line">q=10 or q=40 <span class="memo-mark">✓(3)</span></div>'},
{id:7114,topic:T,question:'Find x-intercepts of $y = 2x^2 + x - 6$ using factorisation.',markingCriteria:[{type:'value',expected:1.5,tolerance:0.01,description:'x=1.5',marks:1},{type:'value',expected:-2,tolerance:0.01,description:'x=-2',marks:1}],easyTemplate:'<div class="memo-line">$2x^2+x-6 = (2x-@INPUT@)(x+@INPUT@) = 0$</div><div class="memo-line">$x = @INPUT@$ or $x = @INPUT@$</div>',hardTemplate:'x=@INPUT@ or x=@INPUT@',memo:'<div class="memo-line">x=3/2=1.5 or x=−2 <span class="memo-mark">✓(2)</span></div>'},
{id:7115,topic:T,question:'Revenue $R = 600q - 3q^2$ and cost $C = 200 + 100q$. Find max profit and corresponding quantity.',markingCriteria:[{type:'value',expected:83.33,tolerance:0.5,description:'q=83.33',marks:2},{type:'value',expected:20633,tolerance:100,description:'Max profit≈R20 633',marks:2}],easyTemplate:'<div class="memo-line">$\\pi = R - C = -3q^2 + @INPUT@q - @INPUT@$</div><div class="memo-line">$\\pi\'= -6q + @INPUT@ = 0$; $q = @INPUT@$</div><div class="memo-line">$\\pi(@INPUT@) \\approx R@INPUT@$</div>',hardTemplate:'q=@INPUT@, Max profit=R@INPUT@',memo:'<div class="memo-line">q≈83.33; profit≈R20 633 <span class="memo-mark">✓(4)</span></div>'},
{id:7116,topic:T,question:'Show that $x^2 + x + 1 = 0$ has no real solutions using the discriminant.',markingCriteria:[{type:'value',expected:-3,tolerance:0.01,description:'Δ=−3',marks:1},{type:'contains',expected:['no real','no solution'],description:'No real roots',marks:1}],easyTemplate:'<div class="memo-line">$\\Delta = (1)^2 - 4(1)(1) = 1 - @INPUT@ = @INPUT@$</div><div class="memo-line">$\\Delta < 0 \\Rightarrow$ @INPUT@</div>',hardTemplate:'Δ=@INPUT@, Result: @INPUT@',memo:'<div class="memo-line">Δ=−3<0 → no real solutions <span class="memo-mark">✓(2)</span></div>'},
{id:7117,topic:T,question:'Write $f(x) = (x-2)(x+6)$ in standard form. State the vertex.',markingCriteria:[{type:'contains',expected:['x² + 4x - 12','x^2+4x-12'],description:'Standard form',marks:1},{type:'value',expected:-2,tolerance:0.01,description:'vertex x=−2',marks:1},{type:'value',expected:-16,tolerance:0.01,description:'vertex y=−16',marks:1}],easyTemplate:'<div class="memo-line">$f(x) = x^2 + @INPUT@x + @INPUT@$</div><div class="memo-line">Vertex: $x = \\frac{-@INPUT@}{2} = @INPUT@$; $f(@INPUT@) = @INPUT@$</div>',hardTemplate:'f(x)=@INPUT@; Vertex(@INPUT@,@INPUT@)',memo:'<div class="memo-line">x²+4x−12; vertex (−2,−16) <span class="memo-mark">✓(3)</span></div>'},
{id:7118,topic:T,question:'A ball is dropped from 80m. Height: $h(t) = 80 - 5t^2$. When does it hit the ground?',markingCriteria:[{type:'value',expected:4,tolerance:0.01,description:'t=4s',marks:2}],easyTemplate:'<div class="memo-line">$0 = @INPUT@ - 5t^2$</div><div class="memo-line">$t^2 = \\frac{@INPUT@}{@INPUT@} = @INPUT@$; $t = @INPUT@$ s</div>',hardTemplate:'t=@INPUT@ seconds',memo:'<div class="memo-line">t=4s <span class="memo-mark">✓(2)</span></div>'},
{id:7119,topic:T,question:'A quadratic $f(x) = x^2 - bx + 16$ has only one root. Find $b$.',markingCriteria:[{type:'anyValue',expected:[8,-8],tolerance:0.01,description:'b=8 or b=-8',marks:3}],easyTemplate:'<div class="memo-line">One root: $\\Delta = 0$</div><div class="memo-line">$b^2 - 4(1)(@INPUT@) = 0$; $b^2 = @INPUT@$; $b = \\pm@INPUT@$</div>',hardTemplate:'b = @INPUT@',memo:'<div class="memo-line">b=±8 <span class="memo-mark">✓(3)</span></div>'},
{id:7120,topic:T,question:'For $f(x) = 3x^2 - 12x + 7$, determine the minimum value of $f$ and the value of $x$ at which it occurs.',markingCriteria:[{type:'value',expected:2,tolerance:0.01,description:'x=2',marks:1},{type:'value',expected:-5,tolerance:0.01,description:'Min=-5',marks:1}],easyTemplate:'<div class="memo-line">$x = \\frac{12}{2(3)} = @INPUT@$</div><div class="memo-line">$f(@INPUT@) = 3(@INPUT@)^2-12(@INPUT@)+7 = @INPUT@-@INPUT@+@INPUT@ = @INPUT@$</div>',hardTemplate:'x=@INPUT@, Min f=@INPUT@',memo:'<div class="memo-line">x=2; f(2)=12−24+7=−5 <span class="memo-mark">✓(2)</span></div>'}
];if(!window.QUESTIONS)window.QUESTIONS=[];window.QUESTIONS.push(...Q);})();

(function(){const T='Week 7: Quadratic Functions',Q=[
{id:7121,topic:T,question:'Solve $x^2 - 5x - 14 = 0$ by factorisation.',markingCriteria:[{type:'value',expected:7,tolerance:0.01,description:'x=7',marks:1},{type:'value',expected:-2,tolerance:0.01,description:'x=-2',marks:1}],easyTemplate:'<div class="memo-line">$(x-@INPUT@)(x+@INPUT@)=0$</div><div class="memo-line">$x=@INPUT@$ or $x=@INPUT@$</div>',hardTemplate:'x=@INPUT@ or x=@INPUT@',memo:'<div class="memo-line">x=7 or x=−2 <span class="memo-mark">✓(2)</span></div>'},
{id:7122,topic:T,question:'A quadratic function has roots at $x=-3$ and $x=5$ and passes through $(0,-15)$. Find the function.',markingCriteria:[{type:'value',expected:1,tolerance:0.01,description:'a=1',marks:1},{type:'contains',expected:['x² - 2x - 15','x^2-2x-15'],description:'f=x²−2x−15',marks:2}],easyTemplate:'<div class="memo-line">$f = a(x+3)(x-5)$; use $(0,-15)$: $-15=a(3)(-5)=@INPUT@a$; $a=@INPUT@$</div><div class="memo-line">$f = (x+@INPUT@)(x-@INPUT@) = @INPUT@$</div>',hardTemplate:'f(x) = @INPUT@',memo:'<div class="memo-line">f=x²−2x−15 <span class="memo-mark">✓(3)</span></div>'},
{id:7123,topic:T,question:'For $f(x) = 2x^2 + 4x - 6$, find all zeros and the vertex.',markingCriteria:[{type:'value',expected:1,tolerance:0.01,description:'x=1',marks:1},{type:'value',expected:-3,tolerance:0.01,description:'x=-3',marks:1},{type:'value',expected:-1,tolerance:0.01,description:'vertex x=-1',marks:1},{type:'value',expected:-8,tolerance:0.01,description:'vertex y=-8',marks:1}],easyTemplate:'<div class="memo-line">Zeros: $2(x^2+2x-3)=2(x+@INPUT@)(x-@INPUT@)=0$; $x=@INPUT@,@INPUT@$</div><div class="memo-line">Vertex: $x=-\\frac{4}{4}=@INPUT@$; $f(@INPUT@)=@INPUT@$</div>',hardTemplate:'Zeros: x=@INPUT@,@INPUT@; Vertex(@INPUT@,@INPUT@)',memo:'<div class="memo-line">zeros: 1, −3; vertex (−1,−8) <span class="memo-mark">✓(4)</span></div>'},
{id:7124,topic:T,question:'Sketch the parabola $y = -(x-2)^2 + 9$. State: vertex, axis, x-intercepts, y-intercept, opening direction.',markingCriteria:[{type:'contains',expected:['(2,9)'],description:'Vertex (2,9)',marks:1},{type:'contains',expected:['x = 2'],description:'Axis x=2',marks:1},{type:'contains',expected:['x=5','x=-1'],description:'x-intercepts',marks:1},{type:'value',expected:5,tolerance:0.01,description:'y-int=5',marks:1},{type:'contains',expected:['down','downward'],description:'Opens down',marks:1}],easyTemplate:'<div class="memo-line">Vertex: $(@INPUT@,@INPUT@)$; Axis: $x=@INPUT@$</div><div class="memo-line">x-ints: $0=-(x-2)^2+9 \\Rightarrow (x-2)^2=9 \\Rightarrow x=@INPUT@,@INPUT@$</div><div class="memo-line">y-int: $-(-2)^2+9=@INPUT@$; Opens @INPUT@</div>',hardTemplate:'Vertex(@INPUT@,@INPUT@), x-ints @INPUT@,@INPUT@',memo:'<div class="memo-line">Vertex(2,9); axis x=2; x-ints 5,−1; y-int 5; opens down <span class="memo-mark">✓(5)</span></div>'}
];if(!window.QUESTIONS)window.QUESTIONS=[];window.QUESTIONS.push(...Q);})();
