// Week 2 supplement — 6 extra Matrix Reduction questions (reach 30+)
(function(){const Q=[
{id:2101,topic:'Week 2: Matrix Reduction',question:'Solve using Gaussian elimination:<br>$4x - 2y = 10$<br>$2x + 3y = 13$',markingCriteria:[{type:'value',expected:3,tolerance:0.01,description:'x=3',marks:2},{type:'value',expected:1,tolerance:0.01,description:'y=1',marks:2}],easyTemplate:'<div class="memo-line">$R_1 \\div 2$: $2x - y = 5$</div><div class="memo-line">$R_2 - R_1$: $(2+2-2)x + (3+1)y = 13+5$ → solve...</div><div class="memo-line">$y = @INPUT@$, $x = @INPUT@$</div>',hardTemplate:'x=@INPUT@, y=@INPUT@',memo:'<div class="memo-line">x=3, y=1 <span class="memo-mark">✓(4)</span></div>'},
{id:2102,topic:'Week 2: Matrix Reduction',question:'A baker makes muffins ($x$) and cookies ($y$). Each muffin needs 2 cups flour and 1 egg; each cookie needs 1 cup flour and 2 eggs. Available: 14 cups flour and 16 eggs. How many of each?',markingCriteria:[{type:'value',expected:4,tolerance:0.01,description:'x=4 muffins',marks:2},{type:'value',expected:6,tolerance:0.01,description:'y=6 cookies',marks:2}],easyTemplate:'<div class="memo-line">$2x+y=14$, $x+2y=16$</div><div class="memo-line">Subtract: $x-y=-2$ → $y = @INPUT@$, $x = @INPUT@$</div>',hardTemplate:'Muffins=@INPUT@, Cookies=@INPUT@',memo:'<div class="memo-line">x=4, y=6 <span class="memo-mark">✓(4)</span></div>'},
{id:2103,topic:'Week 2: Matrix Reduction',question:'Solve by Gaussian elimination:<br>$3x + y = 11$<br>$x - 2y = -3$',markingCriteria:[{type:'value',expected:3,tolerance:0.01,description:'x=3',marks:2},{type:'value',expected:2,tolerance:0.01,description:'y=2',marks:2}],easyTemplate:'<div class="memo-line">$R_1 - 3R_2$: $(0)x + (1+6)y = 11+9$</div><div class="memo-line">$7y = @INPUT@$, $y = @INPUT@$, $x = @INPUT@$</div>',hardTemplate:'x=@INPUT@, y=@INPUT@',memo:'<div class="memo-line">x=3, y=2 <span class="memo-mark">✓(4)</span></div>'},
{id:2104,topic:'Week 2: Matrix Reduction',question:'A cinema sells adult tickets at R120 and child tickets at R75. On Saturday, 320 tickets were sold for R33 300. How many of each type?',markingCriteria:[{type:'value',expected:180,tolerance:0.5,description:'Adult=180',marks:2},{type:'value',expected:140,tolerance:0.5,description:'Child=140',marks:2}],easyTemplate:'<div class="memo-line">$a + c = 320$; $120a + 75c = 33300$</div><div class="memo-line">Substitute: $120(320-c)+75c=33300$</div><div class="memo-line">$-45c = @INPUT@$, $c = @INPUT@$, $a = @INPUT@$</div>',hardTemplate:'Adults=@INPUT@, Children=@INPUT@',memo:'<div class="memo-line">Adults=180, Children=140 <span class="memo-mark">✓(4)</span></div>'},
{id:2105,topic:'Week 2: Matrix Reduction',question:'Write the augmented matrix for the system and solve:<br>$5x - 3y = 7$<br>$2x + y = 8$',markingCriteria:[{type:'value',expected:2.273,tolerance:0.01,description:'x≈2.27',marks:2},{type:'value',expected:3.455,tolerance:0.01,description:'y≈3.45',marks:2}],easyTemplate:'<div class="memo-line">Augmented: $\\begin{bmatrix}5 & -3 & | & 7 \\\\ 2 & 1 & | & 8\\end{bmatrix}$</div><div class="memo-line">$R_1 \\div 5$, then $R_2 - 2R_1$...</div><div class="memo-line">$y = @INPUT@$, $x = @INPUT@$</div>',hardTemplate:'x=@INPUT@, y=@INPUT@',memo:'<div class="memo-line">$11y = 38 \\Rightarrow y \\approx 3.45$, $x \\approx 2.27$ <span class="memo-mark">✓(4)</span></div>'},
{id:2106,topic:'Week 2: Matrix Reduction',question:'A system has no solution (inconsistent). Show that the following is inconsistent:<br>$2x + 4y = 6$<br>$x + 2y = 5$',markingCriteria:[{type:'contains',expected:['inconsistent','no solution','0=4','0 = 4'],description:'Shows 0=4 contradiction',marks:3}],easyTemplate:'<div class="memo-line">Augmented: $\\begin{bmatrix}2 & 4 & | & 6 \\\\ 1 & 2 & | & 5\\end{bmatrix}$</div><div class="memo-line">$R_1 - 2R_2$: $\\begin{bmatrix}0 & 0 & | & @INPUT@\\end{bmatrix}$</div><div class="memo-line">$0 = @INPUT@$ → @INPUT@</div>',hardTemplate:'Result: @INPUT@',memo:'<div class="memo-line">R₁−2R₂: [0 0 | −4] → 0=−4 → Inconsistent <span class="memo-mark">✓(3)</span></div>'}
];if(!window.QUESTIONS)window.QUESTIONS=[];window.QUESTIONS.push(...Q);})();

(function(){const T='Week 2: Matrix Reduction',Q=[
{id:2107,topic:T,question:'Solve using substitution:<br>$y = 2x - 1$<br>$3x + 2y = 12$',markingCriteria:[{type:'value',expected:2,tolerance:0.01,description:'x=2',marks:1},{type:'value',expected:3,tolerance:0.01,description:'y=3',marks:1}],easyTemplate:'<div class="memo-line">Sub $y=2x-1$ into eq2: $3x+2(2x-1)=12$</div><div class="memo-line">$7x=@INPUT@$; $x=@INPUT@$; $y=@INPUT@$</div>',hardTemplate:'x=@INPUT@, y=@INPUT@',memo:'<div class="memo-line">x=2, y=3 <span class="memo-mark">✓(2)</span></div>'},
{id:2108,topic:T,question:'A 2×2 system has the augmented matrix $\\begin{bmatrix}1&-1&|&4\\\\2&1&|&11\\end{bmatrix}$. Solve.',markingCriteria:[{type:'value',expected:5,tolerance:0.01,description:'x=5',marks:1},{type:'value',expected:1,tolerance:0.01,description:'y=1',marks:1}],easyTemplate:'<div class="memo-line">$R_2 - 2R_1$: $[0,3|3] \\Rightarrow y=@INPUT@$</div><div class="memo-line">$x - @INPUT@ = 4 \\Rightarrow x=@INPUT@$</div>',hardTemplate:'x=@INPUT@, y=@INPUT@',memo:'<div class="memo-line">x=5, y=1 <span class="memo-mark">✓(2)</span></div>'},
{id:2109,topic:T,question:'Translate to a system and solve: "The sum of two numbers is 48. The larger is 6 more than twice the smaller."',markingCriteria:[{type:'value',expected:14,tolerance:0.01,description:'smaller=14',marks:1},{type:'value',expected:34,tolerance:0.01,description:'larger=34',marks:1}],easyTemplate:'<div class="memo-line">$x+y=48$; $y=2x+6$</div><div class="memo-line">$x+2x+6=48$; $3x=@INPUT@$; $x=@INPUT@$; $y=@INPUT@$</div>',hardTemplate:'Smaller=@INPUT@, Larger=@INPUT@',memo:'<div class="memo-line">x=14, y=34 <span class="memo-mark">✓(2)</span></div>'},
{id:2110,topic:T,question:'Solve: $\\frac{x}{2} + y = 5$ and $x - \\frac{y}{3} = 4$.',markingCriteria:[{type:'value',expected:4,tolerance:0.01,description:'x=4',marks:1},{type:'value',expected:3,tolerance:0.01,description:'y=3',marks:1}],easyTemplate:'<div class="memo-line">Multiply eq1 by 2: $x+2y=10$</div><div class="memo-line">Multiply eq2 by 3: $3x-y=12$</div><div class="memo-line">Solve: $x=@INPUT@$; $y=@INPUT@$</div>',hardTemplate:'x=@INPUT@, y=@INPUT@',memo:'<div class="memo-line">x=4, y=3 <span class="memo-mark">✓(2)</span></div>'}
];if(!window.QUESTIONS)window.QUESTIONS=[];window.QUESTIONS.push(...Q);})();
