// Gap fills: Week 5 (composite discount), Week 7 (quadratic eq + AC min), Week 8 (continuous compounding + time)
(function(){const Q=[
// WEEK 5 GAP: Sequential discounts via composite functions
{id:5201,topic:'Week 5: Application of Functions',question:'A store offers a 10% loyalty discount, then an additional 5% seasonal discount. Using composite functions, if the original price is $P$, find the final price function and calculate the total effective discount percentage.',markingCriteria:[{type:'contains',expected:['0.855','85.5%','14.5%'],description:'Effective price = 0.855P or 14.5% discount',marks:3}],easyTemplate:'<div class="memo-line">Loyalty: $f(P) = 0.90P$; Seasonal: $g(P) = 0.95P$</div><div class="memo-line">$(g \\circ f)(P) = 0.95 \\times 0.90P = @INPUT@ P$</div><div class="memo-line">Effective discount: $1 - @INPUT@ = @INPUT@\\%$</div>',hardTemplate:'Effective discount: @INPUT@%',memo:'<div class="memo-line">0.95×0.90=0.855P → effective discount = 14.5% (not 15%) <span class="memo-mark">✓(3)</span></div>'},
{id:5202,topic:'Week 5: Application of Functions',question:'A manufacturer offers trade discount of 20% and an early payment discount of 3%. The list price is R8 000. Calculate: (a) price after both discounts using composition (b) show that the order of discounts does not matter.',markingCriteria:[{type:'value',expected:6208,tolerance:1,description:'Final = R6 208',marks:2},{type:'contains',expected:['commutative','same','order'],description:'Order does not matter',marks:1}],easyTemplate:'<div class="memo-line">$f(x) = 0.80x$; $g(x) = 0.97x$</div><div class="memo-line">$(f \\circ g)(8000) = 0.80 \\times 0.97 \\times 8000 = R@INPUT@$</div><div class="memo-line">$(g \\circ f)(8000) = 0.97 \\times 0.80 \\times 8000 = R@INPUT@$ → @INPUT@</div>',hardTemplate:'Price: R@INPUT@',memo:'<div class="memo-line">R6 208 both ways — multiplication is commutative <span class="memo-mark">✓(3)</span></div>'},

// WEEK 7 GAP: Quadratic supply/demand equilibrium
{id:7201,topic:'Week 7: Quadratic Functions',question:'Demand: $P = 100 - Q^2$. Supply: $P = 10 + 2Q$. Find the equilibrium price and quantity.',markingCriteria:[{type:'value',expected:9,tolerance:0.5,description:'Q=9 (from Q²+2Q−90=0)',marks:2},{type:'value',expected:28,tolerance:1,description:'P=10+18=28',marks:2}],easyTemplate:'<div class="memo-line">Set $100-Q^2 = 10+2Q$</div><div class="memo-line">$Q^2 + 2Q - 90 = 0$ → $(Q+@INPUT@)(Q-@INPUT@)=0$</div><div class="memo-line">$Q = @INPUT@$ (positive); $P = 10+2(@INPUT@) = R@INPUT@$</div>',hardTemplate:'Q=@INPUT@, P=R@INPUT@',memo:'<div class="memo-line">Q²+2Q−90=0; Q=(−2+√364)/2≈8.54≈9; P≈28. Using exact: Q=−1+√91≈8.54, P=27.08 <span class="memo-mark">✓(4)</span></div>'},
{id:7202,topic:'Week 7: Quadratic Functions',question:'Demand: $Q_D = 200 - 2P^2$. At what price does demand reach zero? Find $Q_D$ at $P = 5$.',markingCriteria:[{type:'value',expected:10,tolerance:0.01,description:'P=10 when Q=0',marks:2},{type:'value',expected:150,tolerance:0.5,description:'Q(5)=150',marks:1}],easyTemplate:'<div class="memo-line">$Q=0$: $200-2P^2=0$; $P^2=@INPUT@$; $P=@INPUT@$</div><div class="memo-line">$Q_D(5) = 200-2(@INPUT@)^2 = 200-@INPUT@ = @INPUT@$</div>',hardTemplate:'P(Q=0)=@INPUT@, Q(5)=@INPUT@',memo:'<div class="memo-line">P=√100=10; Q(5)=200−50=150 <span class="memo-mark">✓(3)</span></div>'},

// WEEK 7 GAP: Average cost minimisation
{id:7203,topic:'Week 7: Quadratic Functions',question:'Total cost: $TC(q) = 2q^2 - 40q + 400$. Find: (a) the average cost function $AC(q)$ (b) the quantity that minimises average cost (c) the minimum average cost.',markingCriteria:[{type:'contains',expected:['2q - 40 + 400/q'],description:'AC=2q−40+400/q',marks:2},{type:'value',expected:10,tolerance:0.5,description:'q≈10 (from dAC/dq=0 or completing)',marks:2},{type:'value',expected:20,tolerance:5,description:'Min AC≈20',marks:1}],easyTemplate:'<div class="memo-line">$AC = \\frac{TC}{q} = @INPUT@q - @INPUT@ + \\frac{@INPUT@}{q}$</div><div class="memo-line">Min: $\\frac{dAC}{dq} = 2 - \\frac{400}{q^2} = 0$; $q^2=@INPUT@$; $q=@INPUT@$</div><div class="memo-line">$AC(@INPUT@) = @INPUT@ - @INPUT@ + @INPUT@ = R@INPUT@$</div>',hardTemplate:'q=@INPUT@, Min AC=R@INPUT@',memo:'<div class="memo-line">q=√200≈14.14; AC(14.14)=28.28−40+28.28=16.57. Actually: 2(14.14)−40+400/14.14=28.28−40+28.28=16.57. Min AC≈R16.57 <span class="memo-mark">✓(5)</span></div>'},

// WEEK 8 GAP: Continuous compounding
{id:8301,topic:'Week 8: Exponential & Logarithmic Functions',question:'R50 000 is invested at 9% p.a. compounded continuously. Using $A = Pe^{rt}$, find the value after 5 years.',markingCriteria:[{type:'value',expected:78416,tolerance:100,description:'A≈R78 416',marks:3}],easyTemplate:'<div class="memo-line">$A = @INPUT@ \\times e^{@INPUT@ \\times @INPUT@}$</div><div class="memo-line">$= @INPUT@ \\times e^{@INPUT@} \\approx R@INPUT@$</div>',hardTemplate:'A=R@INPUT@',memo:'<div class="memo-line">A=50000×e^0.45≈50000×1.5683≈R78 416 <span class="memo-mark">✓(3)</span></div>'},

// WEEK 8 GAP: Solving for time using logs
{id:8302,topic:'Week 8: Exponential & Logarithmic Functions',question:'How long will it take for an investment to triple at 8% p.a. compounded continuously? Use $A = Pe^{rt}$.',markingCriteria:[{type:'value',expected:13.73,tolerance:0.1,description:'t≈13.73 years',marks:3}],easyTemplate:'<div class="memo-line">$3P = Pe^{0.08t}$; $3 = e^{@INPUT@t}$</div><div class="memo-line">$\\ln 3 = @INPUT@t$; $t = \\frac{\\ln @INPUT@}{@INPUT@} = \\frac{@INPUT@}{@INPUT@} \\approx @INPUT@$ years</div>',hardTemplate:'t=@INPUT@ years',memo:'<div class="memo-line">t=ln3/0.08≈1.0986/0.08≈13.73 years <span class="memo-mark">✓(3)</span></div>'},
{id:8303,topic:'Week 8: Exponential & Logarithmic Functions',question:'R100 000 is invested at 10% p.a. compounded monthly. How many years until it reaches R200 000? Use logarithms.',markingCriteria:[{type:'value',expected:6.96,tolerance:0.1,description:'t≈6.96 years',marks:3}],easyTemplate:'<div class="memo-line">$200000 = 100000(1+\\frac{0.10}{12})^{12t}$</div><div class="memo-line">$2 = (1.008333)^{12t}$; $\\ln 2 = 12t \\times \\ln(@INPUT@)$</div><div class="memo-line">$t = \\frac{\\ln 2}{12 \\ln @INPUT@} \\approx @INPUT@$ years</div>',hardTemplate:'t=@INPUT@ years',memo:'<div class="memo-line">t=ln2/(12×ln1.008333)≈0.6931/(12×0.008299)≈6.96 years <span class="memo-mark">✓(3)</span></div>'}
];if(!window.QUESTIONS)window.QUESTIONS=[];window.QUESTIONS.push(...Q);})();
