(function(){const T='Week 11: Application of Derivatives',Q=[
{id:10101,topic:T,question:'Find $f\'(x)$ for $f(x) = 7x^3 - 5x^2 + 3x - 9$.',markingCriteria:[{type:'contains',expected:['21x²','21x^2'],description:'21x²',marks:1},{type:'contains',expected:['10x','-10x'],description:'-10x',marks:1},{type:'value',expected:3,tolerance:0.01,description:'constant 3',marks:1}],easyTemplate:'<div class="memo-line">$f\'(x) = @INPUT@x^2 - @INPUT@x + @INPUT@$</div>',hardTemplate:'f\'(x) = @INPUT@',memo:'<div class="memo-line">21x²-10x+3 <span class="memo-mark">?(3)</span></div>'},
{id:10102,topic:T,question:'Differentiate $g(x) = \\frac{4}{x^2} + \\sqrt{x}$. Rewrite using exponents first.',markingCriteria:[{type:'contains',expected:['-8x^(-3)','-8/x³'],description:'-8x?³',marks:2},{type:'contains',expected:['0.5x^(-0.5)','1/(2vx)'],description:'1/(2vx)',marks:2}],easyTemplate:'<div class="memo-line">$g = 4x^{-2} + x^{1/2}$</div><div class="memo-line">$g\'= @INPUT@x^{@INPUT@} + @INPUT@x^{@INPUT@}$</div>',hardTemplate:'g\'(x) = @INPUT@',memo:'<div class="memo-line">g\'=-8x?³+0.5x?°·5 <span class="memo-mark">?(4)</span></div>'},
{id:10103,topic:T,question:'Find $\\frac{dy}{dx}$ for $y = (3x+2)(x-5)$. Expand first.',markingCriteria:[{type:'contains',expected:['3x²','3x^2'],description:'3x²',marks:1},{type:'contains',expected:['-13x'],description:'-13x',marks:1},{type:'value',expected:-10,tolerance:0.1,description:'-10',marks:1},{type:'contains',expected:['6x - 13'],description:'dy/dx=6x-13',marks:1}],easyTemplate:'<div class="memo-line">$y = 3x^2 - @INPUT@x - @INPUT@$</div><div class="memo-line">$\\frac{dy}{dx} = @INPUT@x - @INPUT@$</div>',hardTemplate:'dy/dx = @INPUT@',memo:'<div class="memo-line">6x-13 <span class="memo-mark">?(4)</span></div>'},
{id:10104,topic:T,question:'Use chain rule: $h(x) = (4x^2-1)^5$. Find $h\'(x)$.',markingCriteria:[{type:'contains',expected:['5(4x²-1)4','5(4x^2-1)^4'],description:'5(4x²-1)4',marks:2},{type:'contains',expected:['8x','× 8x'],description:'×8x',marks:2}],easyTemplate:'<div class="memo-line">$h\'= @INPUT@(4x^2-1)^{@INPUT@} \\times @INPUT@x$</div><div class="memo-line">$= @INPUT@x(4x^2-1)^4$</div>',hardTemplate:'h\'(x) = @INPUT@',memo:'<div class="memo-line">40x(4x²-1)4 <span class="memo-mark">?(4)</span></div>'},
{id:10105,topic:T,question:'Use product rule: $y = x^2 \\cdot \\ln(x)$. Find $y\'$.',markingCriteria:[{type:'contains',expected:['2x ln x','2x\\ln(x)'],description:'2x ln x',marks:2},{type:'contains',expected:['x²/x','x'],description:'+x',marks:2}],easyTemplate:'<div class="memo-line">$y\' = @INPUT@x \\cdot \\ln(x) + x^2 \\cdot \\frac{@INPUT@}{x}$</div><div class="memo-line">$= @INPUT@x\\ln(x) + @INPUT@$</div>',hardTemplate:'y\' = @INPUT@',memo:'<div class="memo-line">2x ln x + x <span class="memo-mark">?(4)</span></div>'},
{id:10106,topic:T,question:'Quotient rule: $y = \\frac{e^x}{x^2}$. Find $y\'$.',markingCriteria:[{type:'contains',expected:['e^x(x-2)','e^x(x² - 2x)'],description:'Numerator e^x(x-2)',marks:2},{type:'contains',expected:['x^4','x4'],description:'Denominator x4',marks:1}],easyTemplate:'<div class="memo-line">$y\' = \\frac{e^x\\cdot x^2 - e^x \\cdot @INPUT@x}{x^4} = \\frac{e^x(@INPUT@-@INPUT@)}{x^@INPUT@}$</div>',hardTemplate:'y\' = @INPUT@',memo:'<div class="memo-line">e^x(x-2)/x³ <span class="memo-mark">?(3)</span></div>'},
{id:10107,topic:T,question:'Find turning points of $f(x) = 2x^3 - 9x^2 + 12x - 4$ and classify them.',markingCriteria:[{type:'value',expected:1,tolerance:0.01,description:'x=1',marks:1},{type:'value',expected:2,tolerance:0.01,description:'x=2',marks:1},{type:'contains',expected:['local max','maximum at x=1'],description:'Max at x=1',marks:1},{type:'contains',expected:['local min','minimum at x=2'],description:'Min at x=2',marks:1}],easyTemplate:'<div class="memo-line">$f\'= 6x^2-@INPUT@x+@INPUT@ = 0$; $(x-@INPUT@)(x-@INPUT@)=0$</div><div class="memo-line">$x=@INPUT@$: $f\'\'=@INPUT@<0$ ? @INPUT@</div><div class="memo-line">$x=@INPUT@$: $f\'\'=@INPUT@>0$ ? @INPUT@</div>',hardTemplate:'Turning pts: x=@INPUT@(max), x=@INPUT@(min)',memo:'<div class="memo-line">x=1 local max; x=2 local min <span class="memo-mark">?(4)</span></div>'},
{id:10108,topic:T,question:'Cost: $C(q) = 0.02q^3 - 0.6q^2 + 8q + 200$. Find marginal cost at $q=10$.',markingCriteria:[{type:'contains',expected:['0.06q²','0.06q^2'],description:'0.06q²',marks:1},{type:'value',expected:2,tolerance:0.1,description:'MC(10)=R2',marks:2}],easyTemplate:'<div class="memo-line">$MC = C\'(q) = @INPUT@q^2 - @INPUT@q + @INPUT@$</div><div class="memo-line">$MC(10) = @INPUT@(100) - @INPUT@(10) + @INPUT@ = @INPUT@ - @INPUT@ + @INPUT@ = R@INPUT@$</div>',hardTemplate:'MC(10) = R@INPUT@',memo:'<div class="memo-line">MC=6-12+8=R2 <span class="memo-mark">?(3)</span></div>'},
{id:10109,topic:T,question:'Differentiate $f(x) = e^{-2x+1}$.',markingCriteria:[{type:'contains',expected:['-2e^{-2x+1}','-2e^(-2x+1)'],description:'-2e^(-2x+1)',marks:3}],easyTemplate:'<div class="memo-line">$f\'(x) = e^{-2x+1} \\cdot \\frac{d}{dx}(@INPUT@) = @INPUT@e^{-2x+1}$</div>',hardTemplate:'f\'(x) = @INPUT@',memo:'<div class="memo-line">-2e^(-2x+1) <span class="memo-mark">?(3)</span></div>'},
{id:10110,topic:T,question:'$f(x) = \\ln(3x^2 + 1)$. Find $f\'(x)$.',markingCriteria:[{type:'contains',expected:['6x/(3x²+1)','6x/(3x^2+1)'],description:'6x/(3x²+1)',marks:3}],easyTemplate:'<div class="memo-line">$f\'(x) = \\frac{@INPUT@}{@INPUT@}$</div>',hardTemplate:'f\'(x) = @INPUT@',memo:'<div class="memo-line">6x/(3x²+1) <span class="memo-mark">?(3)</span></div>'},
{id:10111,topic:T,question:'Find the equation of the tangent to $y = x^2 + 3x$ at $x = 2$.',markingCriteria:[{type:'value',expected:10,tolerance:0.01,description:'y(2)=10',marks:1},{type:'value',expected:7,tolerance:0.01,description:'slope=7',marks:1},{type:'contains',expected:['y = 7x - 4'],description:'Tangent: y=7x-4',marks:2}],easyTemplate:'<div class="memo-line">$y(2) = @INPUT@$; $y\'= 2x+3$; slope at $x=2$: $@INPUT@$</div><div class="memo-line">$y - @INPUT@ = @INPUT@(x - 2)$ ? $y = @INPUT@x - @INPUT@$</div>',hardTemplate:'y = @INPUT@',memo:'<div class="memo-line">y=7x-4 <span class="memo-mark">?(4)</span></div>'},
{id:10112,topic:T,question:'Revenue $R = 500q$. Cost $C = 200 + 3q^2$. Find MR, MC, and the profit-maximising quantity.',markingCriteria:[{type:'value',expected:500,tolerance:0.01,description:'MR=500',marks:1},{type:'contains',expected:['6q'],description:'MC=6q',marks:1},{type:'value',expected:83.33,tolerance:0.5,description:'q=83.33',marks:2}],easyTemplate:'<div class="memo-line">$MR = R\'= @INPUT@$; $MC = C\'= @INPUT@q$</div><div class="memo-line">$MR=MC$: $@INPUT@ = @INPUT@q$; $q = @INPUT@$</div>',hardTemplate:'MR=@INPUT@, MC=@INPUT@, q=@INPUT@',memo:'<div class="memo-line">MR=500, MC=6q, q˜83.33 <span class="memo-mark">?(4)</span></div>'},
{id:10113,topic:T,question:'$f(x) = \\frac{3x+1}{2x-5}$. Find $f\'(x)$ using the quotient rule. Evaluate $f\'(3)$.',markingCriteria:[{type:'value',expected:-17,tolerance:0.1,description:'Numerator: 3(2x-5)-2(3x+1)=-17',marks:2},{type:'value',expected:-17,tolerance:0.1,description:'f\'(3)=-17',marks:2}],easyTemplate:'<div class="memo-line">$f\' = \\frac{@INPUT@(2x-5) - @INPUT@(3x+1)}{(2x-5)^2} = \\frac{@INPUT@}{(2x-5)^2}$</div><div class="memo-line">$f\'(3) = \\frac{@INPUT@}{(6-5)^2} = @INPUT@$</div>',hardTemplate:'f\'(x) = @INPUT@, f\'(3) = @INPUT@',memo:'<div class="memo-line">f\'=-17/(2x-5)²; f\'(3)=-17 <span class="memo-mark">?(4)</span></div>'},
{id:10114,topic:T,question:'What does $f\'(a) = 0$ tell us geometrically?',markingCriteria:[{type:'contains',expected:['tangent','horizontal','stationary','turning'],description:'Horizontal tangent/stationary point',marks:2}],easyTemplate:'<div class="memo-line">$f\'(a) = 0$ means the tangent at $x=a$ is @INPUT@</div><div class="memo-line">This indicates a @INPUT@ point</div>',hardTemplate:'Meaning: @INPUT@',memo:'<div class="memo-line">Horizontal tangent; stationary/turning point <span class="memo-mark">?(2)</span></div>'},
{id:10115,topic:T,question:'Find the second derivative of $f(x) = 4x^4 - 2x^3 + x$.',markingCriteria:[{type:'contains',expected:['48x²','48x^2'],description:'48x²',marks:1},{type:'contains',expected:['12x','-12x'],description:'-12x',marks:1}],easyTemplate:'<div class="memo-line">$f\'= @INPUT@x^3 - @INPUT@x^2 + @INPUT@$</div><div class="memo-line">$f\'\'= @INPUT@x^2 - @INPUT@x$</div>',hardTemplate:'f\'\'(x) = @INPUT@',memo:'<div class="memo-line">f\'\'=48x²-12x <span class="memo-mark">?(2)</span></div>'},
{id:10116,topic:T,question:'Use the derivative to find if $f(x) = x^3$ is increasing or decreasing at $x=-1$ and $x=2$.',markingCriteria:[{type:'value',expected:3,tolerance:0.01,description:'f\'(-1)=3>0 increasing',marks:1},{type:'value',expected:12,tolerance:0.01,description:'f\'(2)=12>0 increasing',marks:1},{type:'contains',expected:['increasing'],description:'Both increasing',marks:1}],easyTemplate:'<div class="memo-line">$f\'(x) = @INPUT@x^2$</div><div class="memo-line">$f\'(-1) = @INPUT@ > 0$ ? @INPUT@; $f\'(2) = @INPUT@ > 0$ ? @INPUT@</div>',hardTemplate:'At x=-1: @INPUT@; at x=2: @INPUT@',memo:'<div class="memo-line">f\'(x)=3x²; both >0 ? increasing at both points <span class="memo-mark">?(3)</span></div>'}
];if(!window.QUESTIONS)window.QUESTIONS=[];window.QUESTIONS.push(...Q);})();
